Document: ei
Title: Debian ei Manual
Author: <insert document author here>
Abstract: This manual describes what ei is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ei/ei.sgml.gz

Format: postscript
Files: /usr/share/doc/ei/ei.ps.gz

Format: text
Files: /usr/share/doc/ei/ei.text.gz

Format: HTML
Index: /usr/share/doc/ei/html/index.html
Files: /usr/share/doc/ei/html/*.html
