.PHONY: all clean

all:
	$(MAKE) -C atompair
	$(MAKE) -C embedder
	$(MAKE) -C euclidean-search
	$(MAKE) -C matrix
	$(MAKE) -C lshkit

clean:
	$(MAKE) -C atompair clean
	$(MAKE) -C embedder clean 
	$(MAKE) -C euclidean-search clean
	$(MAKE) -C matrix clean
	$(MAKE) -C lshkit clean
