include ../Makefile.inc

CC=$(CXX)

CXXFLAGS += -I../include

LDFLAGS += -L../src 
LDLIBS += -llshkit

SRCS = $(wildcard *.cpp)
OBJS = $(patsubst %.cpp,%.o,$(SRCS))
DEPS = $(patsubst %.o,%.d,$(OBJS))
PROGS = $(OBJS:.o=)

.PHONY:	all clean lib

all:	lib $(PROGS)

lib:
	$(MAKE) -C ../src

.cpp.o:
	$(CXX) -c -MMD -MP $(CXXFLAGS) $< -o $@
	@sed -i -e '1s,\($*\)\.o[ :]*,\1.o $*.d: ,' $*.d

clean:
	rm -f $(OBJS)
	rm -f $(DEPS)
	rm -f $(PROGS)

-include $(DEPS)


